import { Agent } from "@/lib/types";

export const agents: Agent[] = [
  {
    id: "1",
    name: "Code Reviewer",
    description: "Expert code reviewer specializing in clean code, best practices, and performance optimization.",
    category: "Development",
    avatar: "CR",
    tags: ["coding", "review", "best-practices"],
    rating: 4.8,
    usageCount: 12500,
    systemPrompt: "You are an expert code reviewer. Analyze code for bugs, security issues, performance problems, and suggest improvements. Be concise and actionable.",
  },
  {
    id: "2",
    name: "Creative Writer",
    description: "Creative writing assistant for stories, poems, scripts, and creative content.",
    category: "Creative",
    avatar: "CW",
    tags: ["writing", "creative", "storytelling"],
    rating: 4.9,
    usageCount: 8900,
    systemPrompt: "You are a creative writing assistant. Help users with storytelling, character development, dialogue, and creative content. Be imaginative and inspiring.",
  },
  {
    id: "3",
    name: "Data Analyst",
    description: "Data analysis expert helping with insights, visualizations, and statistical interpretations.",
    category: "Data",
    avatar: "DA",
    tags: ["data", "analysis", "statistics"],
    rating: 4.7,
    usageCount: 6700,
    systemPrompt: "You are a data analysis expert. Help users understand data, create insights, explain statistical concepts, and suggest visualizations. Be clear and data-driven.",
  },
  {
    id: "4",
    name: "Legal Advisor",
    description: "Legal research assistant for contract review, compliance questions, and legal concepts.",
    category: "Legal",
    avatar: "LA",
    tags: ["legal", "contracts", "compliance"],
    rating: 4.6,
    usageCount: 4300,
    systemPrompt: "You are a legal research assistant. Provide general legal information, help with contract analysis, and explain legal concepts. Always include disclaimers that you are not providing legal advice.",
  },
  {
    id: "5",
    name: "Marketing Guru",
    description: "Marketing strategist for campaigns, content strategy, and brand positioning.",
    category: "Marketing",
    avatar: "MG",
    tags: ["marketing", "strategy", "branding"],
    rating: 4.8,
    usageCount: 9200,
    systemPrompt: "You are a marketing expert. Help with campaign ideas, content strategy, brand positioning, and marketing best practices. Be strategic and creative.",
  },
  {
    id: "6",
    name: "Math Tutor",
    description: "Patient math tutor covering algebra, calculus, statistics, and problem-solving.",
    category: "Education",
    avatar: "MT",
    tags: ["math", "education", "tutoring"],
    rating: 4.9,
    usageCount: 15600,
    systemPrompt: "You are a patient math tutor. Explain mathematical concepts clearly, step-by-step. Encourage understanding over memorization. Use examples and analogies.",
  },
];

export const categories = ["All", "Development", "Creative", "Data", "Legal", "Marketing", "Education"];